# Generated by Django 4.2.11 on 2026-04-20 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_snippet', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('cwe_id', models.CharField(blank=True, help_text='CWE编号', max_length=20, null=True)),
                ('cwe_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vulnerability_type', models.CharField(blank=True, max_length=100, null=True)),
                ('severity', models.CharField(choices=[('info', '信息'), ('low', '低'), ('medium', '中'), ('high', '高'), ('critical', '严重')], default='medium', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('remediation', models.TextField(blank=True, help_text='修复建议', null=True)),
                ('confidence', models.FloatField(default=0.0, help_text='检测置信度 (0-1)')),
                ('location', models.CharField(blank=True, help_text='漏洞位置', max_length=255, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '代码漏洞',
                'verbose_name_plural': '代码漏洞',
                'ordering': ['-severity', '-confidence'],
            },
        ),
        migrations.CreateModel(
            name='DetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_type', models.CharField(choices=[('phishing', '钓鱼检测'), ('vulnerability', '漏洞检测'), ('combined', '综合检测')], max_length=20)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('input_data', models.TextField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='处理时间（秒）', null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '检测日志',
                'verbose_name_plural': '检测日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectoryScanTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('target_dir', models.CharField(max_length=500)),
                ('languages', models.JSONField(default=list, help_text='扫描的编程语言列表')),
                ('cwe_ids', models.JSONField(blank=True, default=list, help_text='检测的CWE ID列表', null=True)),
                ('total_files', models.IntegerField(default=0)),
                ('scanned_files', models.IntegerField(default=0)),
                ('vulnerable_files', models.IntegerField(default=0)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('progress', models.FloatField(default=0.0, help_text='进度百分比 (0-100)')),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '目录扫描任务',
                'verbose_name_plural': '目录扫描任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='配置键', max_length=100, unique=True)),
                ('value', models.TextField(help_text='配置值（JSON格式）')),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '系统配置',
                'verbose_name_plural': '系统配置',
            },
        ),
        migrations.CreateModel(
            name='WhitelistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('url', 'URL'), ('domain', '域名'), ('ip', 'IP 地址'), ('hash', '文件哈希')], max_length=20)),
                ('value', models.CharField(max_length=500, unique=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('added_by', models.CharField(default='system', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='过期时间，为空表示永久', null=True)),
            ],
            options={
                'verbose_name': '白名单',
                'verbose_name_plural': '白名单',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entry_type', 'value'], name='api_whiteli_entry_t_1fc639_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhishingDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('threat_level', models.CharField(choices=[('safe', '安全'), ('suspicious', '可疑'), ('phishing', '钓鱼'), ('malware', '恶意软件')], max_length=20)),
                ('svm_score', models.FloatField(blank=True, help_text='SVM模型得分', null=True)),
                ('ngram_score', models.FloatField(blank=True, help_text='N-gram模型得分', null=True)),
                ('gte_score', models.FloatField(blank=True, help_text='GTE模型得分', null=True)),
                ('combined_score', models.FloatField(blank=True, help_text='综合得分', null=True)),
                ('model_used', models.CharField(default='combined', max_length=50)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phishing_detail', to='api.detectionlog')),
            ],
            options={
                'verbose_name': '钓鱼检测',
                'verbose_name_plural': '钓鱼检测',
            },
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['-created_at'], name='api_detecti_created_87f6f5_idx'),
        ),
        migrations.AddIndex(
            model_name='detectionlog',
            index=models.Index(fields=['detection_type', '-created_at'], name='api_detecti_detecti_a828ff_idx'),
        ),
        migrations.AddField(
            model_name='codevulnerability',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilities', to='api.detectionlog'),
        ),
    ]
